export const events = [
  {
    title: "React Conf 2026",
    image: "/images/event1.png",
    slug: "react-conf-2026",
    location: "San Francisco, CA",
    date: "March 15-16, 2026",
    time: "9:00 AM - 6:00 PM",
  },
  {
    title: "JSConf EU 2026",
    image: "/images/event2.png",
    slug: "jsconf-eu-2026",
    location: "Berlin, Germany",
    date: "May 20-21, 2026",
    time: "10:00 AM - 7:00 PM",
  },
  {
    title: "Global Hackathon: Code for Climate",
    image: "/images/event3.png",
    slug: "global-hackathon-code-for-climate",
    location: "Online",
    date: "April 10-12, 2026",
    time: "All Day",
  },
  {
    title: "AI in Development Meetup",
    image: "/images/event4.png",
    slug: "ai-in-dev-meetup",
    location: "New York, NY",
    date: "February 28, 2026",
    time: "6:00 PM - 9:00 PM",
  },
  {
    title: "Next.js Conf 2026",
    image: "/images/event5.png",
    slug: "nextjs-conf-2026",
    location: "San Francisco, CA",
    date: "October 25-26, 2026",
    time: "9:00 AM - 6:00 PM",
  },
  {
    title: "Web3 Developer Summit",
    image: "/images/event6.png",
    slug: "web3-dev-summit",
    location: "Amsterdam, Netherlands",
    date: "June 5-7, 2026",
    time: "9:00 AM - 6:00 PM",
  },
];
